#!/bin/sh
#
DEV=$1
OUTDIR=$2
ARGS=$3
if [ "$DEV" = "" ]; then
  DEV=x11
fi

echo heatmap1..
ploticus -prefab heatmap data=curve1.dat y=1 x=2   \
	-$DEV -o ${OUTDIR}heatmap1.$DEV $ARGS

echo heatmap2..
ploticus -prefab heatmap data=snpmap.dat header=yes y=1 x=2 ycats=yes xbinsize=5  \
  colorlist=white,limegreen,green,teal,blue,purple,black \
	-$DEV -o ${OUTDIR}heatmap2.$DEV $ARGS

echo heatmap3..
ploticus -prefab heatmap data=data26 x=1 xcats=yes y=2 ycats=yes contentfield=3  \
	outline="color=black width=5" \
	-$DEV -o ${OUTDIR}heatmap3.$DEV $ARGS

echo heatmap4..
ploticus -prefab heatmap data=data26 x=1 xcats=yes y=2 ycats=yes contentfield=3 symbol="shape=circle \
	radius=0.1" legendsep=0.2 zerocolor=white \
	-$DEV -o ${OUTDIR}heatmap4.$DEV $ARGS
